### ISSUE TITLE
Предлагаю оптимизировать текст в !mge_info

### ISSUE THREAD

**Issue by x9136** [olegsvs/mge_bot#1]
Чтобы стало легче прочитать и меньше мешало читать чат. Если не, тогда можно закрыть Issue.

_Прим: на скринах нет выделения ников в случае сводки и пунктов в случае участника, но в коде есть, потому что так удобней найти нужный ник или пункт._

## Сводка
![Screenshot 2024-07-12 at 18 51 10](https://github.com/user-attachments/assets/4b54af36-527a-4c6e-b9ab-e3e832d8d02e)
↓
![Screenshot 2024-07-12 at 19 05 01](https://github.com/user-attachments/assets/ab03693a-efb6-4d7a-9e80-c78e9f871d43)
```
18:04, ⟳10 мин. **Ходы**: **segall** 3/3 🔴, **RoadHouse** 3/3 [Onee Chanbara ORIGIN], **UncleBjorn** 3/3 [Battlefield 1 ™], **Praden** 3/3 [Flash Back 2], **F1ashko** 3/3 [Sonic Colors: Ultimate],  **BrowJey** 2/3 [The Grinch: Christmas Adventures], **guit88man** 3/3 [BLACK CLOVER: QUARTET KNIGHTS], **UselessMouth** 3/3 [Rollerdrome]. Подробнее: !mge_info ник.
```
## Участник
![Screenshot 2024-07-12 at 18 47 10](https://github.com/user-attachments/assets/f5a82d88-11fb-4d7a-bdfa-8e9384897fdd)
↓
![Screenshot 2024-07-12 at 19 01 19](https://github.com/user-attachments/assets/97f19105-7d8f-4fd8-8b62-c51df455c465)
```
18:04, ⟳10 мин. **Praden** 🟢: УР 1 [0/100], Flash Back 2. 📝**Ходы**: 3/3 дн., 10/10 нед. **Очки**: 0/2 движ., 0/1 разв. **Состояние**: Захват сектора. **Доход**: 0 [1000 на руках]. **Жетоны съезда**: 5. **Полиция**: 0/100. **Мораль**: 6/6. **Эффекты**: +6 4 -0. **HP**: 4/4. **Боевая мощь**: 0/40. https://telegra.ph/MGE-Player-4-07-06
```

**Comment by olegsvs** [comment]
Спасибо, подумаю как улучшить ещё вывод

**Comment by olegsvs** [comment]
Поправил в 3f9efa0fd84fc4068a377e03ef12c8b8f3312cd6
