### ISSUE TITLE
!hltb

### ISSUE THREAD

**Issue by x9136** [olegsvs/mge_bot#2]
Если легко сделать исключение на вызов !hltb для канала, то минор — предлагаю сделать исключение для RoadHouse. У него бот Гарика выдает по такой же команде более подробный ответ на !hltb.

Получается боты дублируют друг друга, хотя не критично.

**Comment by x9136** [comment]
Сделано в другом варианте.

**Comment by olegsvs** [comment]
Увы, команда теперь !mge_hltb
